window.archiveStories=[
 {id:'jan-caracas',month:'January',date:'Jan 3',place:'Caracas',title:'Regime change gets express shipping',facts:'U.S. forces captured Venezuelan leader Nicolás Maduro after military action in Caracas, jolting the region and immediately raising questions about sovereignty and oil.',why:'The operation reshaped Venezuelan politics overnight while Washington made clear that energy interests were part of the conversation.',angle:'Nothing says democratic transition like helicopters, an extraction team and a petroleum spreadsheet.',source:'https://www.reuters.com/business/energy/venezuelas-opposition-soon-lose-citgo-oversight-sources-say-2026-09-09/',amazon:'Venezuela history book'},
 {id:'jan-minnesota',month:'January',date:'Jan 12',place:'Minnesota',title:'Federal surge meets Minnesota nice',facts:'Minnesota sued the Trump administration seeking to block a surge of immigration-enforcement officers after a fatal federal-agent shooting.',why:'The clash turned the state into a national test of federal power, local authority and accountability in immigration enforcement.',angle:'The welcome mat was replaced with a lawsuit.',source:'https://www.reuters.com/video/watch/idRW621412012026RP1/',amazon:'Minnesota travel souvenir'},
 {id:'jan-snow',month:'January',date:'Jan 20',place:'Kamchatka',title:'Russia misplaced several cities under snow',facts:'A major winter storm buried parts of Russia’s Far East beneath extraordinary snowdrifts and disrupted travel across Russia, China and Japan.',why:'The storm showed how a distorted polar vortex can turn regional weather into a three-country transportation failure.',angle:'Parking regulations remain in effect if officials can locate your car.',source:'https://www.reuters.com/business/environment/russias-far-east-buried-snow-transport-disrupted-china-japan-2026-01-20/',amazon:'emergency snow shovel'},
 {id:'jan-shanghai',month:'January',date:'Jan 20',place:'Shanghai',title:'Twenty degrees to snow in one week',facts:'Shanghai saw rare significant snowfall days after unseasonable warmth pushed temperatures near 20°C and prompted early blooms.',why:'The whiplash disrupted roads across multiple provinces and offered a vivid example of increasingly erratic weather.',angle:'Spring preview canceled. Winter has entered the chat.',source:'https://www.reuters.com/business/environment/wave-low-temperature-brings-rare-snowfall-shanghai-2026-01-20/',amazon:'weather station'},
 {id:'jan-doomsday',month:'January',date:'Jan 27',place:'Planet Earth',title:'Doomsday clock requests smaller units',facts:'The Bulletin of the Atomic Scientists moved its symbolic Doomsday Clock to 85 seconds before midnight, the closest reading ever.',why:'Nuclear rivalry, climate danger, biological threats, AI and disinformation all contributed to the assessment.',angle:'Humanity improved its personal best in the wrong direction.',source:'https://www.reuters.com/world/china/atomic-scientists-set-doomsday-clock-closer-midnight-than-ever-2026-01-27/',amazon:'Doomsday Clock book'},

 {id:'feb-shutdown',month:'February',date:'Feb 14',place:'Washington, D.C.',title:'Government closes one department at a time',facts:'Funding expired for the Department of Homeland Security after lawmakers failed to reach agreement over immigration-enforcement policy.',why:'Essential personnel kept working while pay, airport operations and public services became bargaining chips.',angle:'The lights stayed on. The paychecks took a procedural recess.',source:'https://apnews.com/live/donald-trump-news-updates-2-2-2026',amazon:'government shutdown survival mug'},
 {id:'feb-start',month:'February',date:'Feb 5',place:'Moscow / Washington',title:'Nuclear limits expire from lack of interest',facts:'New START, the last nuclear-arms treaty limiting U.S. and Russian strategic arsenals, expired without a replacement.',why:'For the first time in more than half a century, the world’s two largest nuclear arsenals were left without treaty caps.',angle:'Good news: the paperwork burden is down.',source:'https://apnews.com/article/0e82c7fb5e5feca89a9c3f45d6f4feae',amazon:'nuclear arms control history'},
 {id:'feb-ukraine',month:'February',date:'Feb 22',place:'Ukraine',title:'Peace talks receive 1,300 drones',facts:'Russia launched another major wave of missiles and drones at Ukrainian energy infrastructure while diplomatic efforts remained stalled.',why:'Civilian power systems again carried the cost of a war whose negotiations produced little visible movement.',angle:'Moscow submitted its counterproposal at several hundred miles per hour.',source:'https://www.reuters.com/business/energy/russia-hits-ukraine-energy-infrastructure-with-major-missile-drone-strikes-kyiv-2026-02-22/',amazon:'Ukraine history book'},
 {id:'feb-telegram',month:'February',date:'Feb 24',place:'Russia',title:'Telegram receives a government friend request',facts:'Russian authorities opened a criminal investigation involving Telegram founder Pavel Durov while pressuring users toward a state-backed messaging service.',why:'Telegram remains deeply embedded in Russian public life, making control of the platform a major information-power struggle.',angle:'Privacy settings are now managed by the FSB.',source:'https://www.reuters.com/business/media-telecom/russia-investigating-telegram-founder-durov-part-criminal-case-rossiyskaya-2026-02-24/',amazon:'internet privacy book'},
 {id:'feb-olympics',month:'February',date:'Feb 6',place:'Milan–Cortina',title:'The world argues politely on ice',facts:'The 2026 Winter Olympics opened across northern Italy with athletes competing at a geographically spread collection of venues.',why:'The Games combined elite sport with a logistical experiment spanning cities, mountains and thousands of travelers.',angle:'One Olympics. Several zip codes. Infinite shuttle buses.',source:'https://www.olympics.com/en/olympic-games/milano-cortina-2026',amazon:'2026 winter olympics souvenir'},

 {id:'mar-airports',month:'March',date:'Mar 20',place:'U.S. airports',title:'Security line now visible from space',facts:'The prolonged DHS funding impasse left frontline transportation staff working without pay as airport delays and security lines worsened.',why:'A budget fight in Washington became a daily burden for workers and travelers far beyond the Capitol.',angle:'Please arrive three fiscal years before departure.',source:'https://apnews.com/hub/us-government-and-politics',amazon:'travel organizer'},
 {id:'mar-heat',month:'March',date:'Mar 20',place:'Western North America',title:'March skips directly to broil',facts:'An exceptional heatwave broke records across western North America, with researchers finding the event extraordinarily unlikely without human-caused warming.',why:'Early-season heat strains water, agriculture, health systems and wildfire planning before summer even begins.',angle:'Spring was available for six minutes.',source:'https://www.worldweatherattribution.org/',amazon:'portable weather station'},
 {id:'mar-seaice',month:'March',date:'Mar 26',place:'Arctic',title:'Sea ice ties record low, loses tiebreaker',facts:'Scientists reported Arctic winter sea ice at or near the lowest level observed in the satellite record for a second consecutive year.',why:'Winter maximum ice helps regulate climate and protects ecosystems; repeated lows point to long-term structural change.',angle:'The planet has placed the freezer on energy-saving mode.',source:'https://science.nasa.gov/earth/climate-change/',amazon:'climate change atlas'},
 {id:'mar-dhs-deal',month:'March',date:'Mar 27',place:'U.S. Senate',title:'Senate discovers voice vote technology',facts:'Senators advanced a plan to fund most of DHS while separating the most disputed immigration-enforcement funding.',why:'The compromise offered an exit from a record-setting impasse, though the House did not immediately accept it.',angle:'Congress located the off-ramp and then argued over the toll.',source:'https://apnews.com/hub/us-congress',amazon:'Congressional politics book'},
 {id:'mar-ai-money',month:'March',date:'Mar 31',place:'Wall Street',title:'AI spending discovers infinity',facts:'Investors kept pouring money into artificial-intelligence infrastructure while questioning whether returns could keep pace with the scale of spending.',why:'The boom increasingly shaped energy demand, chip supply, corporate borrowing and the wider stock market.',angle:'Step one: spend everything. Step two: ask the chatbot.',source:'https://www.reuters.com/technology/artificial-intelligence/',amazon:'artificial intelligence book'},

 {id:'apr-pyramid',month:'April',date:'Apr 20',place:'Teotihuacan',title:'World heritage site becomes crime scene',facts:'A gunman opened fire on tourists at Mexico’s Teotihuacan pyramids, killing one person and injuring others before taking his own life.',why:'The attack prompted heightened security planning ahead of the World Cup and scrutiny of online extremist influences.',angle:'The ancient civilization deserved better visitors.',source:'https://apnews.com/article/3f4e43decf5559a438b4cd89ae3a3eca',amazon:'Teotihuacan history book'},
 {id:'apr-robots',month:'April',date:'Apr 19',place:'Beijing',title:'Robots enter half-marathon, regret cardio',facts:'Humanoid robots raced alongside people in Beijing in a public demonstration of China’s rapidly developing robotics industry.',why:'The spectacle exposed both the progress and the awkward limitations of machines being pushed into human environments.',angle:'Several robots immediately understood why humans drive.',source:'https://www.reuters.com/technology/',amazon:'humanoid robot kit'},
 {id:'apr-dhs-end',month:'April',date:'Apr 30',place:'Washington, D.C.',title:'Record shutdown finally finds an ending',facts:'Congress approved funding that ended the prolonged Department of Homeland Security shutdown.',why:'The impasse disrupted airports, delayed pay and made routine government operations depend on an extended partisan standoff.',angle:'The government reopened after locating the government.',source:'https://apnews.com/hub/us-congress',amazon:'government bureaucracy book'},
 {id:'apr-lichens',month:'April',date:'Apr 30',place:'A laboratory',title:'Space industry hires lichens',facts:'Researchers explored lab-grown lichens as a possible ingredient in future off-world manufacturing systems.',why:'Biological materials could help astronauts make useful products without launching every raw material from Earth.',angle:'Mars colonization proudly sponsored by stuff on a rock.',source:'https://www.reuters.com/science/',amazon:'lichen terrarium kit'},
 {id:'apr-fire-season',month:'April',date:'Apr 8',place:'United States',title:'Fire season declines to wait for summer',facts:'Record warmth and dry conditions pushed parts of the United States toward elevated fire risk unusually early in the year.',why:'Longer fire seasons raise costs and reduce the time communities have to prepare and recover.',angle:'The calendar has been outsourced to the atmosphere.',source:'https://www.noaa.gov/climate',amazon:'wildfire emergency kit'},

 {id:'may-longview',month:'May',date:'May 26',place:'Longview, Washington',title:'Profit meets the cost it never budgets',facts:'A catastrophic incident at a Longview paper mill killed workers and left families and investigators searching for answers.',why:'Industrial disasters force scrutiny of maintenance, safety culture and who carries the consequences when systems fail.',angle:'The quarterly report did not include the human line item.',source:'https://www.kptv.com/2026/05/30/officials-say-remains-all-9-missing-workers-found-ided-after-deadly-longview-chemical-spill-death-toll-11/',amazon:'workplace safety book'},
 {id:'may-moonbase',month:'May',date:'May 26',place:'The Moon',title:'NASA discusses the upstairs addition',facts:'NASA leadership outlined plans for a sustained lunar presence and the systems required to support a future Moon base.',why:'A permanent foothold would change exploration, science and the competition among spacefaring nations.',angle:'No atmosphere. Excellent school district.',source:'https://www.nasa.gov/moon-to-mars/',amazon:'moon base model kit'},
 {id:'may-telescope',month:'May',date:'May 22',place:'Space',title:'New telescope asks universe to hold still',facts:'NASA prepared a new space telescope intended to survey the sky and investigate major questions about cosmic history.',why:'Wide surveys can reveal patterns and rare objects that narrow observations miss.',angle:'Humanity bought a better camera for the existential crisis.',source:'https://science.nasa.gov/universe/',amazon:'astronomy telescope'},
 {id:'may-hantavirus',month:'May',date:'May 22',place:'A disease laboratory',title:'Scientists meet another virus nobody ordered',facts:'Researchers used laboratory and field work to understand a hantavirus outbreak and improve detection.',why:'Fast genomic and epidemiological work can keep a regional outbreak from becoming a wider emergency.',angle:'Nature has released another limited-edition pathogen.',source:'https://www.reuters.com/science/',amazon:'epidemiology book'},
 {id:'may-icebot',month:'May',date:'May 29',place:'Frozen lakes',title:'Robot gets the worst lake assignment',facts:'Engineers demonstrated an underwater robot designed to monitor lake ice more safely than sending people onto unstable surfaces.',why:'Better data can protect communities and researchers as warming makes ice conditions harder to predict.',angle:'The robot drew the short straw because it has no union.',source:'https://www.reuters.com/science/',amazon:'underwater drone'},

 {id:'jun-worldcup',month:'June',date:'Jun 11',place:'North America',title:'Forty-eight teams enter one group chat',facts:'The expanded FIFA World Cup opened across the United States, Canada and Mexico with more teams, venues and travel than any prior edition.',why:'The tournament became a continent-scale test of transportation, security, heat planning and ticket affordability.',angle:'The beautiful game now includes a connecting flight.',source:'https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026',amazon:'2026 world cup soccer ball'},
 {id:'jun-ufo',month:'June',date:'Jun 12',place:'The Pentagon',title:'UFO disclosure includes suspicious potato',facts:'Newly released government files described unexplained discs, glowing orbs and one object compared to a shimmering potato.',why:'The records added detail without providing conclusive evidence of extraterrestrial life or a government cover-up.',angle:'We crossed the galaxy and all we got was this airborne russet.',source:'https://apnews.com/article/34c2a9b294e94a972f352df42c4a17ae',amazon:'UFO investigation book'},
 {id:'jun-bacteria',month:'June',date:'Jun 10',place:'United Kingdom',title:'Bacteria told to start paying utilities',facts:'A British startup demonstrated technology that draws small amounts of electricity from living bacteria.',why:'Bioelectrochemical systems could eventually power low-energy sensors in places where batteries are impractical.',angle:'Microbes have joined the gig economy.',source:'https://www.reuters.com/science/',amazon:'microbiology science kit'},
 {id:'jun-georgia',month:'June',date:'Jun 26',place:'Georgia parliament',title:'Annual report becomes contact sport',facts:'Georgian lawmakers brawled in parliament during the prime minister’s annual report amid deep political tensions.',why:'The fight offered a blunt picture of institutional breakdown in a country already divided over its political direction.',angle:'The minutes will reflect several amendments by fist.',source:'https://www.reuters.com/world/',amazon:'parliamentary procedure book'},
 {id:'jun-uk',month:'June',date:'Jun 29',place:'United Kingdom',title:'Prime minister-in-waiting enters the queue',facts:'A leadership crisis pushed British politics toward another transition as challengers promised to reset the government.',why:'Leadership churn can rapidly reshape policy, markets and the country’s relationship with its allies.',angle:'Downing Street has begun charging by the hour.',source:'https://www.reuters.com/world/uk/',amazon:'British politics book'},

 {id:'jul-worldcup-final',month:'July',date:'Jul 20',place:'New Jersey',title:'Spain wins, FIFA survives the ceremony',facts:'Spain defeated Argentina in the World Cup final after a tournament marked by huge crowds, heat, security concerns and political theater.',why:'The expanded tournament proved the event’s global pull while revealing the scale of hosting it across a continent.',angle:'Ninety minutes of football followed by several hours of dignitaries.',source:'https://www.reuters.com/sports/soccer/',amazon:'Spain soccer jersey'},
 {id:'jul-starmer',month:'July',date:'Jul 15',place:'United Kingdom',title:'Another British premiership reaches checkout',facts:'Keir Starmer’s departure capped a political crisis and opened the way for a new Labour leader.',why:'Another leadership change added to Britain’s recent pattern of shortened mandates and rapid resets.',angle:'Please leave the keys to Number 10 at reception.',source:'https://www.reuters.com/world/uk/',amazon:'British prime ministers book'},
 {id:'jul-lepen',month:'July',date:'Jul 7',place:'France',title:'Campaign trail includes ankle accessory',facts:'Marine Le Pen returned to presidential campaigning while facing legal restrictions and intense scrutiny.',why:'Her continued candidacy tested how France balances voter choice, court judgments and far-right momentum.',angle:'The campaign merchandise now pairs with GPS.',source:'https://www.reuters.com/world/europe/',amazon:'French politics book'},
 {id:'jul-farage',month:'July',date:'Jul 7',place:'United Kingdom',title:'Farage finds another exit',facts:'Nigel Farage moved to resign as an MP amid scrutiny of political finances and pressure on his party.',why:'The turmoil threatened a movement built heavily around his personal brand and electoral appeal.',angle:'Brexit means Brexit. Resign means check again tomorrow.',source:'https://www.reuters.com/world/uk/',amazon:'Brexit history book'},
 {id:'jul-starship',month:'July',date:'Jul 17',place:'Texas',title:'Starship aborts before adding another crater',facts:'SpaceX aborted a Starship launch seconds before liftoff during final countdown operations.',why:'The stop showed the tension between rapid test schedules and the safety systems meant to catch problems before ignition.',angle:'The rocket practiced the rare maneuver called restraint.',source:'https://www.reuters.com/science/',amazon:'SpaceX Starship model'},

 {id:'aug-telescope',month:'August',date:'Aug 30',place:'Space',title:'NASA launches the universe’s new auditor',facts:'NASA launched a telescope designed to map vast regions of the sky and investigate the structure and history of the universe.',why:'Its surveys could sharpen measurements of dark matter, dark energy and how galaxies evolved.',angle:'The universe has been notified that receipts are required.',source:'https://science.nasa.gov/universe/',amazon:'NASA telescope model'},
 {id:'aug-cockroach',month:'August',date:'Aug 28',place:'A rescue lab',title:'Cyborg cockroach applies for first responder',facts:'Researchers demonstrated electronically guided cockroaches that could carry sensors into dangerous, confined spaces.',why:'Tiny living platforms can reach rubble and voids that conventional rescue robots cannot.',angle:'Humanity finally found a job that improves the cockroach’s reputation.',source:'https://www.reuters.com/science/',amazon:'robot insect kit'},
 {id:'aug-urine',month:'August',date:'Aug 27',place:'United Kingdom',title:'Startup closes the pee loop',facts:'A British startup showed a system that converts urine into fertilizer through a process marketed as “pee-cycling.”',why:'Recovering nutrients from waste could reduce treatment costs and dependence on energy-intensive fertilizer production.',angle:'The circular economy has entered the bathroom.',source:'https://www.reuters.com/sustainability/',amazon:'home composting kit'},
 {id:'aug-binface',month:'August',date:'Aug 14',place:'United Kingdom',title:'Democracy narrowly avoids sharing a stage',facts:'Nigel Farage won an election while novelty candidate Count Binface again supplied Britain’s traditional dose of ballot-box absurdity.',why:'Satirical candidates remain a surprisingly durable way to puncture the ceremony surrounding political power.',angle:'The bin had a platform. The platform had better branding.',source:'https://www.reuters.com/world/uk/',amazon:'Count Binface book'},
 {id:'aug-nigeria',month:'August',date:'Aug 27',place:'Nigeria',title:'Mass kidnapping tests another promise',facts:'A large kidnapping placed new pressure on Nigeria’s government amid continuing insecurity.',why:'Repeated abductions undermine trust, education and economic life while exposing gaps between official promises and local safety.',angle:'The security plan remains safely stored in a press release.',source:'https://www.reuters.com/world/africa/',amazon:'Nigeria history book'},

 {id:'sep-typhoon',month:'September',date:'Sep 4',place:'Coastal China',title:'The seventh typhoon is apparently the charm',facts:'Typhoon Saudel brought torrential rain, flooding, evacuations and building collapses to coastal China.',why:'The storm added to an unusually intense season and raised the risk of landslides and prolonged displacement.',angle:'The small-weather-event label was printed before the water arrived.',source:'https://www.reuters.com/business/environment/typhoon-saudel-brings-torrential-rain-flooding-chinas-coastal-areas-2026-09-04/',amazon:'emergency weather radio'},
 {id:'sep-nepal',month:'September',date:'Sep 9',place:'Nepal',title:'Climate justice arrives with an invoice',facts:'After a catastrophic glacier-linked flood, Nepal sought billions in international aid and framed the request as climate justice.',why:'Countries contributing least to warming often lack the resources to absorb its most severe consequences.',angle:'The smallest emitter has been handed the largest cleanup bill.',source:'https://www.reuters.com/business/environment/nepal-puts-climate-justice-centre-global-pitch-flood-aid-2026-09-09/',amazon:'Nepal travel guide'},
 {id:'sep-citgo',month:'September',date:'Sep 9',place:'Venezuela / United States',title:'Citgo custody battle reaches another season',facts:'Venezuela’s opposition moved toward losing oversight of U.S. refiner Citgo as political recognition and court proceedings shifted.',why:'Control of the profitable refiner links Venezuela’s political crisis directly to creditors, sanctions and U.S. energy interests.',angle:'National sovereignty now comes with a refinery rewards card.',source:'https://www.reuters.com/business/energy/venezuelas-opposition-soon-lose-citgo-oversight-sources-say-2026-09-09/',amazon:'oil industry history book'},
 {id:'sep-iaea',month:'September',date:'Sep 9',place:'Vienna',title:'Nuclear watchdog forwards thread to Security Council',facts:'The IAEA board reported Iran to the U.N. Security Council over failures to cooperate with inquiries into undeclared nuclear material.',why:'The move escalated a dispute already entangled with war, inspections and the risk of further nuclear proliferation.',angle:'The international community has selected Reply All.',source:'https://apnews.com/article/607ecdffcd8ef88ddf8f33041e86b720',amazon:'nuclear diplomacy book'},
 {id:'sep-huawei',month:'September',date:'Sep 10',place:'New York',title:'Two-decade tech fight finally gets a courtroom',facts:'The U.S. racketeering case against Huawei opened with prosecutors alleging theft, sanctions violations and misuse of financial systems.',why:'The trial concentrates years of U.S.–China technology and security tensions into a single federal courtroom.',angle:'Terms and conditions have requested a jury trial.',source:'https://apnews.com/article/0597e888ed45d692330ebb967d82b0c0',amazon:'cybersecurity book'}
];
