window.dailyStories=[
 {"id":"sep11-tallest-horse","isoDate":"2026-09-11","month":"September","date":"Sep 11, 2026","place":"Towcester, England","image":"assets/cards/sep11-tallest-horse.svg","title":"World’s tallest living horse now needs upstairs neighbors","facts":"Hugo, a four-year-old Shire horse in Towcester, England, has been recognized in Guinness World Records 2027 as the world’s tallest living horse. A veterinarian measured him without horseshoes at 1.99 meters—about 6 feet 6 inches—at the withers.","why":"Shire horses were bred for heavy work and are among the world’s largest horse breeds. Hugo is still young, gentle and reportedly affectionate, meaning the record holder is essentially an enormous dog whose food comes by the bale.","angle":"Hugo is tall enough to inspect the second floor without entering the building. His owner does not lead him into a stable; she asks the stable for clearance.","amazonLinks":[{"title":"Guinness World Records 2027","image":"https://m.media-amazon.com/images/P/1806500256.01.LZZZZZZZ.jpg","alt":"Guinness World Records 2027 book","quip":"The official book containing Hugo’s new record—and several pages sturdy enough to serve as his coaster.","url":"https://www.amazon.com/dp/1806500256?tag=blappos-20"},{"title":"The Horse Encyclopedia","image":"https://m.media-amazon.com/images/P/1465451439.01.LZZZZZZZ.jpg","alt":"The Horse Encyclopedia book","quip":"A complete horse reference that may need a foldout page to accommodate Hugo.","url":"https://www.amazon.com/dp/1465451439?tag=blappos-20"},{"title":"Big Red Barn","image":"https://m.media-amazon.com/images/P/006443009X.01.LZZZZZZZ.jpg","alt":"Big Red Barn children’s book","quip":"Finally, a barn title that begins to acknowledge Hugo’s minimum housing requirements.","url":"https://www.amazon.com/dp/006443009X?tag=blappos-20"}],"source":"https://noticias.uol.com.br/meio-ambiente/ultimas-noticias/redacao/2026/09/10/cavalo-de-quase-dois-metros-supera-marca-e-vira-o-mais-alto-vivo-do-mundo.ghtm","sourceName":"Read the report"},
 {"id":"sep11-prince-william-croc","isoDate":"2026-09-11","month":"September","date":"Sep 11, 2026","place":"Queensland, Australia","image":"assets/cards/sep11-prince-william-croc.svg","title":"Prince William is now a 12-foot crocodile, technically","facts":"Robert Irwin announced that the 300th crocodile tagged in a long-running conservation study at the Steve Irwin Wildlife Reserve has been named Prince William. The 12-foot-6-inch saltwater crocodile will carry a tracker for the next decade.","why":"Researchers will use the tracker to study the crocodile’s movements, diet, body temperature and social behavior. Irwin chose the royal name to recognize the Prince of Wales’s conservation work and the Earthshot Prize.","angle":"Britain has finally produced a royal who can settle constitutional questions with a death roll. Palace staff describe him as reserved, traditional and extremely difficult to fit for trousers.","amazonLinks":[{"title":"The Earthshot Prize: A Handbook for Dreamers and Thinkers","image":"https://m.media-amazon.com/images/P/1526364697.01.LZZZZZZZ.jpg","alt":"The Earthshot Prize handbook","quip":"The conservation handbook behind the work that earned Prince William the rare honor of becoming a giant crocodile.","url":"https://www.amazon.com/dp/1526364697?tag=blappos-20"},{"title":"Crocodiles by Seymour Simon","image":"https://m.media-amazon.com/images/P/0064438295.01.LZZZZZZZ.jpg","alt":"Crocodiles by Seymour Simon book","quip":"Background reading for distinguishing the future king from the other 299 research subjects.","url":"https://www.amazon.com/dp/0064438295?tag=blappos-20"},{"title":"National Geographic Readers: Crocodiles","image":"https://m.media-amazon.com/images/P/1426319479.01.LZZZZZZZ.jpg","alt":"National Geographic Readers Crocodiles book","quip":"A beginner’s guide to royal protocol when the receiving line is twelve feet long and heavily armored.","url":"https://www.amazon.com/dp/1426319479?tag=blappos-20"}],"source":"https://people.com/robert-irwin-names-crocodile-after-prince-william-12076627","sourceName":"Read the People report"},
  {id:'sep10-narrowest-car',isoDate:'2026-09-10',month:'September',date:'Sep 10, 2026',place:'Global',image:'assets/cards/sep10-narrowest-car.webp',title:'World’s narrowest drivable car leaves elbow room off the blueprint',magnetUrl:'https://blappos.printify.me/product/31868618',magnetPrice:'$9.99',facts:'Guinness World Records marked the arrival of its 2027 annual book by announcing a collection of new record holders, including the world’s narrowest drivable car. It is a functioning vehicle, not merely a tiny display model.',why:'Record vehicles are usually optimized around one extreme. Making a car extraordinarily narrow while keeping it drivable turns ordinary packaging—steering, controls, wheels and a human driver—into the entire engineering challenge.',angle:'At last, a car for drivers who look at a bicycle lane and complain about all the wasted real estate. The glove compartment has been replaced by one glove.',amazonLinks:[{"title":"Drop Stop Car Seat Gap Fillers — Set of 2","image":"https://m.media-amazon.com/images/I/71aaOjmFYtL._AC_SL1440_.jpg","alt":"Two Drop Stop car seat gap fillers","quip":"The world’s narrowest car solves the seat-gap problem by nearly eliminating the possibility of a gap.","url":"https://www.amazon.com/dp/B00BYH6C1E?tag=blappos-20"},{"title":"HOTOR Compact 2-Gallon Car Trash Can","image":"https://m.media-amazon.com/images/I/51wza8T539L._AC_SL1500_.jpg","alt":"HOTOR compact car trash can","quip":"A compact bin for a car whose entire cabin may already qualify as compact storage.","url":"https://www.amazon.com/dp/B07VGRVKSN?tag=blappos-20"},{"title":"Ampper 2-Inch Blind Spot Mirrors — Pack of 2","image":"https://m.media-amazon.com/images/I/71hWoORU83L._AC_SL1500_.jpg","alt":"Pair of Ampper round blind spot mirrors","quip":"Two-inch mirrors for a car so narrow the blind spot may be wider than the vehicle.","url":"https://www.amazon.com/dp/B01CV4ANCC?tag=blappos-20"}],source:'https://www.upi.com/Odd_News/',sourceName:'Read the UPI Odd News report'},
 {id:'sep10-monitor-lizard',isoDate:'2026-09-10',month:'September',date:'Sep 10, 2026',place:'Missouri',image:'assets/cards/sep10-monitor-lizard.webp',title:'Missouri storm drain reveals unexpected dragon setting',magnetUrl:'https://blappos.printify.me/product/31868644',magnetPrice:'$9.99',facts:'An Asian water monitor lizard was fished out of a storm drain in Missouri. The large reptile is not native to the state, making the underground encounter considerably stranger than the usual clogged-drain call.',why:'Asian water monitors are powerful, semiaquatic lizards commonly kept in the exotic-pet trade. Outside their native range, a loose animal can pose a difficult rescue problem for both the reptile and the people trying to retrieve it safely.',angle:'Missouri checked the storm drain and discovered the municipal sewer package had quietly upgraded to include dragons. The alligators-in-the-sewer union has filed a jurisdictional complaint.',amazonLinks:[{"title":"National Geographic Readers: Lizards","image":"https://m.media-amazon.com/images/P/1426309228.01.LZZZZZZZ.jpg","alt":"National Geographic Readers Lizards book","quip":"A quick identification guide for confirming that the animal in the drain is wildly outside Missouri’s normal specifications.","url":"https://www.amazon.com/dp/1426309228?tag=blappos-20"},{"title":"Ultimate Reptileopedia: The Most Complete Reptile Reference Ever","image":"https://m.media-amazon.com/images/P/1426321023.01.LZZZZZZZ.jpg","alt":"Ultimate Reptileopedia reference book","quip":"The full reference for when one storm-drain lizard turns a routine call into an exotic-species exam.","url":"https://www.amazon.com/dp/1426321023?tag=blappos-20"},{"title":"National Geographic Kids Everything Reptiles","image":"https://m.media-amazon.com/images/P/1426313683.01.LZZZZZZZ.jpg","alt":"National Geographic Kids Everything Reptiles book","quip":"Required reading after Missouri plumbing unexpectedly begins issuing dragons.","url":"https://www.amazon.com/dp/1426313683?tag=blappos-20"}],source:'https://www.upi.com/Odd_News/',sourceName:'Read the UPI Odd News report'},
 {id:'sep10-marmot-coolant',isoDate:'2026-09-10',month:'September',date:'Sep 10, 2026',place:'San Francisco, California',image:'assets/cards/sep10-marmot-coolant.webp',title:'Mystery marmot treats radiator fluid like a tasting menu',magnetUrl:'https://blappos.printify.me/product/31868361',magnetPrice:'$9.99',facts:'A mystery marmot found in San Francisco reportedly drank radiator fluid and required help from animal-care professionals. The unusual rescue became one of September 10’s standout odd-news stories.',why:'Antifreeze can be dangerously toxic to animals, and wildlife that wanders around vehicles may encounter leaked automotive fluids. The episode is funny as a headline but also a reminder to clean spills and keep chemicals secured.',angle:'The marmot arrived in San Francisco, skipped the sourdough and went directly to the fluorescent-green house special. The sommelier has been dismissed.',amazonLinks:[{"title":"OTOTO Baby Nessie Tea Infuser","image":"https://m.media-amazon.com/images/I/71x3v3kOFFL._AC_SL1500_.jpg","alt":"Baby Nessie loose-leaf tea infuser","quip":"For beverages that should be steeped, served and—unlike radiator fluid—approved for mammals.","url":"https://www.amazon.com/dp/B01DHUJAKU?tag=blappos-20"},{"title":"Ostrichpillow Original Travel Pillow","image":"https://m.media-amazon.com/images/I/71mYkyZFA-L._AC_SL1500_.jpg","alt":"Ostrichpillow Original travel pillow","quip":"Post-tasting hibernation equipment for anyone overwhelmed by the coolant menu.","url":"https://www.amazon.com/dp/B00B4S6SLW?tag=blappos-20"},{"title":"The Screaming Goat (Book & Figure)","image":"assets/products/screaming-goat.jpg","alt":"The Screaming Goat miniature book and figure","quip":"A compact automotive warning system programmed to scream when wildlife approaches the radiator.","url":"https://www.amazon.com/dp/0762459816?tag=blappos-20"}],source:'https://www.upi.com/Odd_News/',sourceName:'Read the UPI Odd News report'},
 {id:'sep9-airforce-slide',isoDate:'2026-09-09',month:'September',date:'Sep 9, 2026',place:'Joint Base Andrews, Maryland',image:'assets/cards/sep9-airforce-slide.webp',title:'Air Force One deploys the exit before the president boards',magnetUrl:'https://blappos.printify.me/product/31867302',magnetPrice:'$9.99',facts:'President Donald Trump’s departure for Dallas was briefly delayed after an emergency slide deployed from the new Air Force One while the aircraft sat at Joint Base Andrews. Reuters reported that military personnel accidentally triggered the slide; crews removed it and the flight departed.',why:'Emergency slides are single-use equipment that must be removed and serviced after deployment, so an accidental inflation can turn a normal departure into an expensive tarmac reset. No emergency was reported and the trip continued.',angle:'The plane apparently heard “boarding begins” and selected “evacuate.” Nothing says presidential transportation like arriving at the jet and finding it has already tried to leave without you.',amazonLinks:[{"title":"Ostrichpillow Original Travel Pillow","image":"https://m.media-amazon.com/images/I/71mYkyZFA-L._AC_SL1500_.jpg","alt":"Ostrichpillow Original travel pillow","quip":"For travelers who want to evacuate from consciousness before the slide evacuates itself.","url":"https://www.amazon.com/dp/B00B4S6SLW?tag=blappos-20"},{"title":"Wacky Waving Inflatable Tube Guy","image":"https://m.media-amazon.com/images/I/71xmJjfakxL._SL1500_.jpg","alt":"Mini wacky waving inflatable tube guy","quip":"A pocket-size reenactment of what the aircraft did on the tarmac.","url":"https://www.amazon.com/dp/0762462876?tag=blappos-20"},{"title":"Air Force One: The Aircraft That Shaped the Modern Presidency","image":"https://m.media-amazon.com/images/P/1559718943.01.LZZZZZZZ.jpg","alt":"Air Force One history book","quip":"The serious reference guide, presumably with a chapter titled “Please Do Not Pull That.”","url":"https://www.amazon.com/dp/1559718943?tag=blappos-20"}],source:'https://www.reuters.com/world/trump-says-emergency-slide-is-being-checked-qatar-gifted-air-force-one-2026-09-09/',sourceName:'Read the Reuters report'},
 {id:'sep9-nicolas-sinkhole',isoDate:'2026-09-09',month:'September',date:'Sep 9, 2026',place:'Malibu, California',image:'assets/cards/sep9-nicolas-sinkhole.webp',title:'Nicolas Cage’s driveway gets a basement it did not order',magnetUrl:'https://blappos.printify.me/product/31867646',magnetPrice:'$9.99',facts:'A large sinkhole opened beneath the driveway of a beachfront Malibu home reportedly owned by Nicolas Cage, damaging the property and helping trigger evacuation orders along Sea Level Drive. Officials said the hole grew to roughly 25–30 feet deep and about 30 by 60 feet wide.',why:'The collapse followed severe surf, tides and coastal erosion associated with the remnants of Hurricane Marie. Authorities restricted access because the expanding void threatened homes, utilities and emergency access.',angle:'Nicolas Cage has survived stolen declarations, face swaps and a wicker-man situation. The driveway finally found a plot twist he had not already filmed.',amazonLinks:[{"title":"Voodoo Child — Created by Nicolas Cage and Weston Cage","image":"assets/products/voodoo-9780981480800.jpg","alt":"Voodoo Child graphic novel created by Nicolas Cage and Weston Cage","quip":"The actual Cage-created graphic novel, for a driveway disaster that already sounds like his next movie.","url":"https://www.amazon.com/dp/0981480802?tag=blappos-20"},{"title":"Nicolas Cage Reversible Sequin Pillow Cover","image":"https://m.media-amazon.com/images/I/81vF6TXYz-L._AC_SL1500_.jpg","alt":"Nicolas Cage reversible sequin pillow cover","quip":"Brush the sequins and reveal the only face qualified to stare into a 30-foot sinkhole.","url":"https://www.amazon.com/dp/B0CP3HDM6N?tag=blappos-20"},{"title":"Nicolas Cage Coloring Book","image":"https://m.media-amazon.com/images/P/B0BSJ6FSS5.01.LZZZZZZZ.jpg","alt":"Unofficial Nicolas Cage novelty coloring book","quip":"Color inside the lines while Malibu declines to do the same.","url":"https://www.amazon.com/dp/B0BSJ6FSS5?tag=blappos-20"}],source:'https://apnews.com/article/2bd3a67b83f46e79d0b78b5d462fb7fa',sourceName:'Read the AP report'},
 {id:'sep9-goat',isoDate:'2026-09-09',month:'September',date:'Sep 9, 2026',place:'Snohomish County, Washington',image:'assets/cards/sep9-goat.webp',title:'Escaped goat becomes acting neighborhood security director',magnetUrl:'https://blappos.printify.me/product/31867947',magnetPrice:'$9.99',facts:'Snohomish County sheriff’s deputies were called to wrangle an escaped goat with roughly one-foot horns after residents reported it was trying to ram people. Body-camera video captured deputies physically steering the very determined animal back into its pen.',why:'Nobody was reported seriously hurt, but residents stayed inside while deputies handled the animal. The sheriff’s office described the goat as taking its role as neighborhood menace very seriously.',angle:'For one afternoon the cul-de-sac had a new HOA president. Dues were payable in hay and all complaints were handled forehead-first.',amazonLinks:[{"title":"The Screaming Goat (Book & Figure)","image":"assets/products/screaming-goat.jpg","alt":"The Screaming Goat miniature book and screaming goat figure","quip":"A desk-size witness who can provide the neighborhood’s official statement.","url":"https://www.amazon.com/dp/0762459816?tag=blappos-20"},{"title":"The Little Book of Goat Yoga","image":"https://m.media-amazon.com/images/P/1473698499.01.LZZZZZZZ.jpg","alt":"The Little Book of Goat Yoga","quip":"De-escalation training for horned HOA presidents, now with breathing exercises.","url":"https://www.amazon.com/dp/1473698499?tag=blappos-20"},{"title":"The Screaming Christmas Goat","image":"https://m.media-amazon.com/images/P/0762482893.01.LZZZZZZZ.jpg","alt":"The Screaming Christmas Goat book and figure","quip":"Because one screaming goat is a news story; two is a seasonal collection.","url":"https://www.amazon.com/dp/0762482893?tag=blappos-20"}],source:'https://www.upi.com/Odd_News/2026/09/09/Snohomish-County-Washington-escaped-goat/5371788965345/',sourceName:'Read the UPI report'},
 {id:'sep9-hotdog',isoDate:'2026-09-09',month:'September',date:'Sep 9, 2026',place:'Kansas City, Missouri',image:'assets/cards/sep9-hotdog.webp',title:'Baseball crowd completes emergency stadium hot-dog assembly',magnetUrl:'https://blappos.printify.me/product/31867951',magnetPrice:'$9.99',facts:'Kansas City Royals fans had 35 seconds to bounce a giant inflatable hot dog and giant inflatable bun through separate sections of Kauffman Stadium and unite them. They pulled it off, earning free hot dogs for the crowd.',why:'The “Home Bun Race” happened during a Royals game against Toronto and became exactly the kind of low-stakes collective achievement the internet was built to preserve forever.',angle:'Thousands of people briefly achieved perfect coordination for the most American objective available: put the enormous meat tube in the enormous bread before time expires.',amazonLinks:[{"title":"GOOSH Inflatable Hot Dog Costume","image":"assets/products/inflatable-hot-dog.jpg","alt":"Adult inflatable hot dog costume","quip":"The emergency backup frank, should the stadium bun fail to achieve contact.","url":"https://www.amazon.com/dp/B0DPX57JBP?tag=blappos-20"},{"title":"The Great American Hot Dog Book","image":"https://m.media-amazon.com/images/P/1423600223.01.LZZZZZZZ.jpg","alt":"The Great American Hot Dog Book","quip":"Required reading before thousands of strangers assemble lunch by crowd-surfing.","url":"https://www.amazon.com/dp/1423600223?tag=blappos-20"},{"title":"Vlasic Dill Pickle Corn Puffs","image":"https://m.media-amazon.com/images/I/71c4xfpiQVL._SL1500_.jpg","alt":"Bag of Vlasic dill pickle flavored corn puffs","quip":"For anyone whose hot dog toppings must also arrive as airborne stadium snacks.","url":"https://www.amazon.com/dp/B0DGZ93J34?tag=blappos-20"}],source:'https://www.upi.com/Odd_News/2026/09/09/home-bun-race-Kansas-City-royals/8641788970720/',sourceName:'Read the UPI report'},
 {id:'sep9-boa-engine',isoDate:'2026-09-09',month:'September',date:'Sep 9, 2026',place:'West Allis, Wisconsin',image:'assets/cards/sep9-boa-engine.webp',title:'Wisconsin mechanic discovers one hose has opinions',magnetUrl:'https://blappos.printify.me/product/31867952',magnetPrice:'$9.99',facts:'A West Allis family inspecting a car engine spotted what first looked like a dirty hose. Then it turned and looked back. The object was a roughly four-foot boa constrictor wedged into the engine compartment.',why:'Animal-control officials brought in a reptile rescue, whose founder eventually coaxed the snake out. The boa was placed on a stray hold while officials looked for an owner.',angle:'This is why the repair manual says “inspect belts and hoses” but never says “maintain eye contact with them.”',amazonLinks:[{"title":"OTOTO Baby Nessie Tea Infuser","image":"https://m.media-amazon.com/images/I/71x3v3kOFFL._AC_SL1500_.jpg","alt":"Baby Nessie loose-leaf tea infuser","quip":"A friendlier serpentine object to discover lurking in a hot liquid compartment.","url":"https://www.amazon.com/dp/B01DHUJAKU?tag=blappos-20"},{"title":"There’s a Snake in My School!","image":"https://m.media-amazon.com/images/P/0008172706.01.LZZZZZZZ.jpg","alt":"There’s a Snake in My School children’s book","quip":"Close enough—just replace “school” with “engine bay” and add a mechanic screaming off-page.","url":"https://www.amazon.com/dp/0008172706?tag=blappos-20"},{"title":"Wearable Shark Blanket","image":"https://m.media-amazon.com/images/I/51WyCFq0XUL._AC_SL1000_.jpg","alt":"Wearable shark blanket sleeping bag","quip":"For people who saw four feet of reptile under the hood and wanted to lose to a different animal.","url":"https://www.amazon.com/dp/B0CH9TWC91?tag=blappos-20"}],source:'https://www.upi.com/Odd_News/2026/09/09/boa-constrictor-car-hood-West-Allis-Wisconsin/5751788971514/',sourceName:'Read the UPI report'},
 {id:'sep9-recliner-dog',isoDate:'2026-09-09',month:'September',date:'Sep 9, 2026',place:'Joppatowne, Maryland',image:'assets/cards/sep9-recliner-dog.webp',title:'Terrier loses argument with recliner; firefighters escalate immediately',magnetUrl:'https://blappos.printify.me/product/31867957',magnetPrice:'$9.99',facts:'A rescue terrier named Highway became so badly tangled inside a recliner that firefighters from the Joppa Magnolia Volunteer Fire Company brought in hydraulic rescue equipment. They used the Jaws of Life to free the dog before he was taken for emergency veterinary care.',why:'Reclining furniture contains moving metal mechanisms and tight internal spaces that can be dangerous for pets that crawl underneath or inside. The rescue drew a wave of similar pet-owner stories online.',angle:'Highway entered the chair looking for a nap and accidentally unlocked the full vehicle-extrication package.',amazonLinks:[{"title":"Chenille Dog Hand Towel","image":"https://m.media-amazon.com/images/I/612tJq5VD2L._AC_SL1500_.jpg","alt":"Fluffy chenille dog-shaped hand towel","quip":"A tiny dog engineered to hang safely outside the furniture.","url":"https://www.amazon.com/dp/B0FRLKDX1J?tag=blappos-20"},{"title":"Dog Shaming","image":"https://m.media-amazon.com/images/P/0385349343.01.LZZZZZZZ.jpg","alt":"Dog Shaming humor book","quip":"Highway’s sign: “I made the recliner require hydraulic rescue equipment.”","url":"https://www.amazon.com/dp/0385349343?tag=blappos-20"},{"title":"BBQ Meat Shredder Claws","image":"https://m.media-amazon.com/images/I/71Z0h08fPtL._AC_SL1500_.jpg","alt":"Pair of barbecue meat shredder claws","quip":"The household edition of the Jaws of Life—do not test this theory on the chair.","url":"https://www.amazon.com/dp/B01N5U14FA?tag=blappos-20"}],source:'https://people.com/firefighters-rescue-dog-trapped-inside-recliner-in-maryland-12111746',sourceName:'Read the People report'},
 {id:'sep9-disc-golf',isoDate:'2026-09-09',month:'September',date:'Sep 9, 2026',place:'Idaho',image:'assets/cards/sep9-disc-golf.webp',title:'Disc golfers make relaxation stressful in 41.33 seconds',magnetUrl:'https://blappos.printify.me/product/31867960',magnetPrice:'$9.99',facts:'David Rush, Travis Davidson, Oliver Davidson and Anders Davidson set the Guinness World Records mark for the fastest hole of disc golf by a team of four, completing the attempt in 41.33 seconds.',why:'The record required accurate throws and a final uphill sprint to put the disc in the basket, turning a leisurely park sport into something much closer to a fire drill.',angle:'They successfully answered the question nobody asked: what if disc golf had the cardiovascular atmosphere of missing a flight?',amazonLinks:[{"title":"Towch Disc Golf Towel Pouch","image":"https://m.media-amazon.com/images/I/417bNYXoWdL.jpg","alt":"Black Towch disc golf towel pouch","quip":"Carries three to five discs, which is apparently enough equipment for a 41-second emergency.","url":"https://www.amazon.com/dp/B00YADXB36?tag=blappos-20"},{"title":"Zen & the Art of Disc Golf","image":"https://m.media-amazon.com/images/P/1502779331.01.LZZZZZZZ.jpg","alt":"Zen and the Art of Disc Golf book","quip":"A calm, centered rebuttal to turning the park into a four-person fire drill.","url":"https://www.amazon.com/dp/1502779331?tag=blappos-20"},{"title":"Dance Party Button","image":"https://m.media-amazon.com/images/I/61bqFwxDgmL._AC_SL1500_.jpg","alt":"Light-up dance party sound button","quip":"Smack it at 41.34 seconds and let the tiny victory ceremony begin.","url":"https://www.amazon.com/dp/B09LDB1SV9?tag=blappos-20"}],source:'https://www.guinnessworldrecords.com/openvideo/v/david-rush-sets-new-world-record-for-hot-dog-toss',sourceName:'See the Guinness World Records listing'},
 {id:'sep9-lottery',isoDate:'2026-09-09',month:'September',date:'Sep 9, 2026',place:'White Plains, Maryland',image:'assets/cards/sep9-lottery.webp',title:'Woman plays same lottery numbers for 20 years and finally wins the argument',magnetUrl:'https://blappos.printify.me/product/31867966',magnetPrice:'$9.99',facts:'A Maryland woman who said she had played the same Bonus Match 5 numbers for about two decades bought three tickets with the same combination for one drawing. All three hit the $50,000 prize, giving her a total of $150,000.',why:'The winner told lottery officials she had to call her sister to confirm the numbers because she did not believe what she was seeing. She said the money would go toward projects around the house.',angle:'Twenty years of “these numbers are due” has officially been upgraded from questionable math to family legend.',amazonLinks:[{"title":"Lottery Winning Strategies & 70 Percent Win Formula","image":"https://m.media-amazon.com/images/P/094576023X.01.LZZZZZZZ.jpg","alt":"Lottery Winning Strategies book","quip":"For anyone who wants to turn “same numbers for 20 years” into a written business plan.","url":"https://www.amazon.com/dp/094576023X?tag=blappos-20"},{"title":"The Lottery and Other Stories","image":"https://m.media-amazon.com/images/P/0374529531.01.LZZZZZZZ.jpg","alt":"The Lottery and Other Stories by Shirley Jackson","quip":"Not a financial guide, but certainly the most ominous way to celebrate a winning ticket.","url":"https://www.amazon.com/dp/0374529531?tag=blappos-20"},{"title":"The Winner","image":"https://m.media-amazon.com/images/P/1538711796.01.LZZZZZZZ.jpg","alt":"The Winner novel by David Baldacci","quip":"A title accurate enough to display beside three identical $50,000 tickets.","url":"https://www.amazon.com/dp/1538711796?tag=blappos-20"}],source:'https://www.upi.com/Odd_News/2026/09/09/lotto-Maryland-Lottery-20-years-Bonus-Match-5/6381788975567/',sourceName:'Read the UPI report'}
];

const verifiedSourceCorrections={
 'sep10-narrowest-car':{source:'https://www.youtube.com/watch?v=M_IFdyBrWQA',sourceName:'Watch the Guinness World Records report'},
 'sep9-disc-golf':{source:'https://www.youtube.com/shorts/7-ih0vd9hMQ',sourceName:'Watch the Guinness World Records attempt'}
};
window.dailyStories.forEach(story=>Object.assign(story,verifiedSourceCorrections[story.id]||{}));

window.dailyFinds=[
 {storyId:'sep10-marmot-coolant',title:'Prestone AF-1420 Antifreeze/Coolant Tester',image:'https://images-na.ssl-images-amazon.com/images/P/B000BOA9RY.01.LZZZZZZZ.jpg',alt:'Prestone antifreeze and coolant tester',quip:'For checking the radiator’s vintage before the local marmot appoints itself coolant sommelier.',url:'https://www.amazon.com/dp/B000BOA9RY?tag=blappos-20'},
 {storyId:'sep10-marmot-coolant',title:'Loraffe 12V/24V Ultrasonic Under Hood Rodent Repellent — 2 Pack',image:'https://m.media-amazon.com/images/I/51yhzOPYWKL._AC_SL1000_.jpg',alt:'Loraffe ultrasonic under-hood animal repeller two-pack',quip:'A tiny nightclub for your engine bay: ultrasonic noise, flashing lights and absolutely no marmot reservations.',url:'https://www.amazon.com/dp/B07D118ZRJ?tag=blappos-20'},
 {storyId:'sep10-marmot-coolant',title:'GOLENER Oil Spill Mat — 29 by 36 Inches',image:'https://m.media-amazon.com/images/I/71QMqrgG-KL._AC_SL1500_.jpg',alt:'GOLENER absorbent automotive fluid spill mat',quip:'Catch the fluorescent buffet before wildlife discovers the driveway tasting menu.',url:'https://www.amazon.com/dp/B0D2XVTTML?tag=blappos-20'},
 {storyId:'sep9-goat',title:'The Screaming Goat (Book & Figure)',image:'assets/products/screaming-goat.jpg',alt:'The Screaming Goat miniature book and screaming goat figure',quip:'For anyone who read “horned neighborhood menace” and thought: put that on my desk.',url:'https://www.amazon.com/dp/0762459816?tag=blappos-20'},
 {storyId:'sep9-nicolas-sinkhole',title:'Voodoo Child — Created by Nicolas Cage and Weston Cage',image:'assets/products/voodoo-9780981480800.jpg',alt:'Voodoo Child graphic novel created by Nicolas Cage and Weston Cage',quip:'The actual graphic novel created by Nicolas Cage—because apparently a collapsing Malibu driveway was not enough plot.',url:'https://www.amazon.com/dp/0981480802?tag=blappos-20'},
 {storyId:'sep9-hotdog',title:'GOOSH Inflatable Hot Dog Costume Adult Food Funny Halloween Blow Up Costume',image:'assets/products/inflatable-hot-dog.jpg',alt:'GOOSH adult inflatable hot dog costume',quip:'The emergency backup hot dog, should the stadium bun fail to achieve contact.',url:'https://www.amazon.com/dp/B0DPX57JBP?tag=blappos-20'}
];

// Sep. 10 verification pass: only stories with exact dated sources and three
// directly matched, image-first Amazon cards remain eligible for publication.
const tallestHorse=window.dailyStories.find(story=>story.id==='sep11-tallest-horse');
Object.assign(tallestHorse,{
 isoDate:'2026-09-10',
 date:'Sep 10, 2026',
 image:'assets/cards/sep10-tallest-horse.webp',
 facts:'Hugo, a four-year-old Shire horse in Towcester, England, was recognized in Guinness World Records 2027 as the world’s tallest living horse. A veterinarian measured him without horseshoes at 1.99 meters—about 6 feet 6 inches—at the withers.',
 why:'Shire horses were bred for heavy work and are among the world’s largest horse breeds. Hugo is still young, gentle and reportedly affectionate, while the breed itself is now critically endangered.',
 amazonLinks:[
  {title:'Guinness World Records 2027',image:'https://m.media-amazon.com/images/I/71v6YTBS-HL._SL1200_.jpg',alt:'Cover of the Guinness World Records 2027 book',quip:'The official record book containing Hugo’s new title—and several pages sturdy enough to serve as his coaster.',salesPriority:5,url:'https://www.amazon.com/dp/1806500256?tag=blappos-20'},
  {title:'The Horse Encyclopedia (DK Pet Encyclopedias)',image:'https://m.media-amazon.com/images/I/71nQ+QPJ6nL._SL1500_.jpg',alt:'Cover of The Horse Encyclopedia from DK',quip:'A complete horse reference that may need a foldout page to accommodate Hugo.',salesPriority:4,url:'https://www.amazon.com/dp/1465451439?tag=blappos-20'},
  {title:'Encyclopedia of Horse Breeds',image:'https://m.media-amazon.com/images/I/61fFs6ixLVL._SL1000_.jpg',alt:'Cover of Encyclopedia of Horse Breeds by Hendricks',quip:'For identifying the Shire breed before the specimen peers into your second-floor window.',salesPriority:3,url:'https://www.amazon.com/dp/080613884X?tag=blappos-20'}
 ],
 source:'https://people.com/hugo-the-shire-horse-claims-title-of-world-s-tallest-horse-12115531',
 sourceName:'Read the People report'
});

const princeCroc=window.dailyStories.find(story=>story.id==='sep11-prince-william-croc');
Object.assign(princeCroc,{
 isoDate:'2026-09-02',
 date:'Sep 2, 2026',
 image:'assets/cards/sep11-prince-william-croc.webp'
});
princeCroc.amazonLinks.forEach((item,index)=>item.salesPriority=[4,3,3][index]);

const narrowCar=window.dailyStories.find(story=>story.id==='sep10-narrowest-car');
Object.assign(narrowCar,{
 place:'Bagnolo Cremasco, Italy',
 facts:'Italian mechanic Andrea Marazzi turned a salvaged 1993 Fiat Panda into the world’s narrowest drivable car. The electric “Flat Fiat” is 50.20 centimeters (19.76 inches) wide, has four wheels, one headlight and one seat, and retains more than 90 percent of the original car’s parts.',
 why:'Marazzi spent about a year fitting a driver, steering, controls and a working powertrain into a slice of car. The finished vehicle weighs about 264 kilograms, reaches roughly 15 km/h and is not street legal.',
 amazonLinks:[
  {title:'Drop Stop - Original Car Seat Gap Filler (Shark Tank) - Set of 2 + Gifts',image:'https://m.media-amazon.com/images/I/71aaOjmFYtL._AC_SL1440_.jpg',alt:'Pair of black Drop Stop car seat gap fillers',quip:'For the one-seat Flat Fiat, where losing anything beside the seat may count as exterior storage.',salesPriority:5,url:'https://www.amazon.com/dp/B00BYH6C1E?tag=blappos-20'},
  {title:'Ampper Blind Spot Mirror, 2" Round HD Glass Frameless Convex Rear View Mirror, Pack of 2',image:'https://m.media-amazon.com/images/I/71hWoORU83L._AC_SL1500_.jpg',alt:'Pair of Ampper two-inch round blind-spot mirrors',quip:'Two-inch mirrors for a car so narrow the blind spot may be wider than the vehicle.',salesPriority:4,url:'https://www.amazon.com/dp/B01CV4ANCC?tag=blappos-20'},
  {title:'Guinness World Records 2027',image:'https://m.media-amazon.com/images/I/71v6YTBS-HL._SL1200_.jpg',alt:'Cover of the Guinness World Records 2027 book',quip:'The record book that makes the 19.76-inch Flat Fiat officially more than a very committed door.',salesPriority:5,url:'https://www.amazon.com/dp/1806500256?tag=blappos-20'}
 ],
 source:'https://www.thesun.co.uk/news/40340374/mechanic-smashes-world-record-narrowest-car/',
 sourceName:'Read The Sun report'
});

const ponyCollection={
 id:'sep10-pony-collection',
 isoDate:'2026-09-10',
 month:'September',
 date:'Sep 10, 2026',
 place:'Lowestoft, England',
 image:'assets/cards/sep10-pony-collection.webp',
 title:'Denied one horse, woman acquires 7,500 ponies instead',
 facts:'Miranda Worby of Lowestoft, England, earned a Guinness World Record after 4,550 My Little Pony items were officially counted. She told People that the collection has since grown to around 7,500 pieces, filling a room and a storage unit.',
 why:'Worby began collecting the toys at age three and started hunting seriously for missing pieces in 1997. The record is a spectacular example of how a childhood “no” can become a decades-long cataloging operation.',
 angle:'Her parents declined to buy one horse. The appeal process has now produced roughly 7,499 additional exhibits and an off-site evidence locker.',
 amazonLinks:[
  {title:'My Little Pony Classics - Celestial Ponies - Polaris - Retro 4" Collectible Play Figure, Great for Kids, Toddlers, Adults, Girls and Boys Ages 3+',image:'https://m.media-amazon.com/images/I/81swiGDUiYL._AC_SL1500_.jpg',alt:'My Little Pony Classics Celestial Ponies Polaris retro collectible figure',quip:'One more pony for a collection whose “one more” phase has lasted nearly three decades.',salesPriority:5,url:'https://www.amazon.com/dp/B0BPK2351F?tag=blappos-20'},
  {title:'Ponyville Confidential: The History and Culture of My Little Pony, 1981-2016',image:'https://m.media-amazon.com/images/I/61bK5gTn9wL._SL1360_.jpg',alt:'Cover of Ponyville Confidential, a history of My Little Pony',quip:'The field guide for understanding how a toy shelf evolves into municipal-scale pony infrastructure.',salesPriority:4,url:'https://www.amazon.com/dp/1476662096?tag=blappos-20'},
  {title:'Guinness World Records 2027',image:'https://m.media-amazon.com/images/I/71v6YTBS-HL._SL1200_.jpg',alt:'Cover of the Guinness World Records 2027 book',quip:'The official paperwork confirming that 7,500 ponies is a record, not a home-decor preference.',salesPriority:5,url:'https://www.amazon.com/dp/1806500256?tag=blappos-20'}
 ],
 source:'https://people.com/woman-told-she-couldnt-have-horse-as-child-breaks-record-worlds-biggest-my-little-pony-collection-12115528',
 sourceName:'Read the People report'
};

window.dailyStories=window.dailyStories.filter(story=>!['sep10-monitor-lizard','sep10-marmot-coolant'].includes(story.id));
window.dailyStories.splice(window.dailyStories.indexOf(narrowCar)+1,0,ponyCollection);
window.dailyFinds=[];
