const stories=[
 {id:'coastal-china',place:'Coastal China',date:'Sep 4, 2026',image:'assets/cards/coastal-china.webp',title:'The seventh typhoon is apparently the charm',dek:'Typhoon Saudel brought flooding, evacuations and building collapses to coastal China—another entry in an unusually punishing storm season.',source:'https://www.reuters.com/business/environment/typhoon-saudel-brings-torrential-rain-flooding-chinas-coastal-areas-2026-09-04/',sourceName:'Read the Reuters report'},
 {id:'nepal',place:'Nepal',date:'Sep 9, 2026',image:'assets/cards/nepal.webp',title:'Climate justice arrives with a $5 billion invoice',dek:'After a catastrophic glacier-linked flood, Nepal is seeking international aid and arguing that countries contributing least to warming are paying the highest price.',source:'https://www.reuters.com/business/environment/nepal-puts-climate-justice-centre-global-pitch-flood-aid-2026-09-09/',sourceName:'Read the Reuters report'},
 {id:'australia',place:'Australia',date:'Jan 30, 2026',image:'assets/cards/australia.webp',title:'Summer has breached the warranty',dek:'Parts of South Australia reached 50°C during a record-breaking heatwave. The tourism board did not, to our knowledge, adopt this slogan.',source:'https://www.facebook.com/bureauofmeteorology/videos/738793718949974/',sourceName:'See the Bureau of Meteorology update'},
 {id:'longview',place:'Longview, Washington',date:'May 30, 2026',image:'assets/cards/longview.webp',title:'The mill disaster behind “Not Fit for Profit”',dek:'A deadly industrial incident at a Longview paper mill left workers dead and a community demanding answers. The card targets corporate accountability; the loss is real.',source:'https://www.kptv.com/2026/05/30/officials-say-remains-all-9-missing-workers-found-ided-after-deadly-longview-chemical-spill-death-toll-11/',sourceName:'Read the local report'},
 {id:'washington',place:'Washington, D.C.',date:'Feb 2, 2026',image:'assets/cards/washington.webp',title:'Congress briefly discovers the out-of-office reply',dek:'A funding fight triggered a partial federal shutdown while lawmakers argued over the bill that would reopen the government.',source:'https://apnews.com/live/donald-trump-news-updates-2-2-2026',sourceName:'Read the AP coverage'},
 {id:'caracas',place:'Caracas',date:'Jan 3, 2026',image:'assets/cards/caracas.webp',title:'Regime change, now with express checkout',dek:'U.S. military action in Venezuela and the capture of Nicolás Maduro turned a years-long crisis into an even larger argument over sovereignty, oil and power.',source:'https://www.reuters.com/business/energy/venezuelas-opposition-soon-lose-citgo-oversight-sources-say-2026-09-09/',sourceName:'Read the Reuters follow-up'},
 {id:'minneapolis',place:'Minneapolis',date:'Jan 2026',image:'assets/cards/minneapolis.webp',title:'Public safety, some assembly required',dek:'Federal immigration enforcement operations and protests put Minneapolis back at the center of a national fight over force, oversight and who gets called dangerous.',source:'https://apnews.com/hub/immigration',sourceName:'Follow AP immigration coverage'},
 {id:'el-paso',place:'El Paso',date:'2026',image:'assets/cards/el-paso.webp',title:'Drone panic: airspace closed, questions open',dek:'A security alert involving drone activity disrupted flights and revived the familiar ritual of closing first and explaining later.',source:'https://www.faa.gov/newsroom',sourceName:'Check FAA news'},
 {id:'kuwait',place:'Kuwait',date:'2026',image:'assets/cards/kuwait.webp',title:'Friendly fire remains badly branded',dek:'The phrase has always done heroic work making catastrophic military mistakes sound like an awkward office email.',source:'https://apnews.com/hub/middle-east',sourceName:'Follow AP Middle East coverage'},
 {id:'small-potatoes',place:'Washington, D.C.',date:'2026',image:'assets/cards/small-potatoes.webp',title:'Tiny accountability, family-size consequences',dek:'When officials call a scandal “small potatoes,” Blappos hears a merchandising opportunity and a warning about lowered expectations.',source:'https://apnews.com/hub/us-government-and-politics',sourceName:'Follow AP politics coverage'}
];
const grid=document.querySelector('#card-grid');
const dialog=document.querySelector('#story-dialog');
const content=document.querySelector('#story-content');
const archiveStories=window.archiveStories||[];
const allStories=[...stories,...archiveStories];
const AMAZON_TAG='blappos-20';
function amazonUrl(terms){return `https://www.amazon.com/s?k=${encodeURIComponent(terms||'news history books')}&tag=${AMAZON_TAG}`}
function card(story,index){return `<button class="news-card" data-story="${story.id}"><img src="${story.image}" alt="Satirical illustrated travel magnet for ${story.place}" width="1000" height="1000" ${index>2?'loading="lazy"':''}><span class="card-meta"><span>${story.place}</span><span>${story.date}</span></span><h3>${story.title}</h3><span class="read">FLIP FOR THE REAL STORY →</span></button>`}
grid.innerHTML=stories.map(card).join('');
function openStory(id){const story=allStories.find(item=>item.id===id);if(!story)return;const facts=story.facts||story.dek;const why=story.why||'The event became part of a larger argument about public responsibility, power and the cost carried by ordinary people.';const angle=story.angle||story.title;const visual=story.image?`<img src="${story.image}" alt="Satirical illustrated travel magnet for ${story.place}" width="1000" height="1000">`:'';content.innerHTML=`<article class="story ${story.image?'':'no-image'}">${visual}<div class="story-copy"><span class="label">THE STORY BEHIND THE SATIRE · ${story.place} · ${story.date}</span><h2 id="story-title">${story.title}</h2><h4>What happened</h4><p>${facts}</p><h4>Why it matters</h4><p>${why}</p><h4>The Blappos angle</h4><p>${angle}</p><a class="source" href="${story.source}" target="_blank" rel="noopener">${story.sourceName||'Read the reporting'} ↗</a><a class="shop-link" href="${amazonUrl(story.amazon||story.place+' history book')}" target="_blank" rel="sponsored noopener">RELATED BOOKS & GEAR ON AMAZON ↗</a><p class="shop-note">As an Amazon Associate, Blappos may earn from qualifying purchases.</p><p class="disclosure">Blappos is commentary. Artwork is illustration—not documentary photography—and the joke is not a substitute for the linked reporting.</p></div></article>`;dialog.showModal();history.replaceState(null,'',`#${id}`)}
document.addEventListener('click',event=>{const trigger=event.target.closest('[data-story]');if(trigger)openStory(trigger.dataset.story)});
document.querySelector('.close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
dialog.addEventListener('close',()=>history.replaceState(null,'',location.pathname));
const archiveGrid=document.querySelector('#archive-grid');
const filters=document.querySelector('#month-filters');
const months=[...new Set(archiveStories.map(story=>story.month))];
function archiveCard(story){return `<button class="wire-card" data-story="${story.id}"><span class="wire-top"><span>${story.place}</span><span>${story.date}</span></span><h3>${story.title}</h3><p>${story.angle}</p><span class="read">READ THE FULL WRITE-UP →</span></button>`}
function renderArchive(month='All'){archiveGrid.innerHTML=archiveStories.filter(story=>month==='All'||story.month===month).map(archiveCard).join('');document.querySelectorAll('#month-filters button').forEach(button=>button.classList.toggle('active',button.dataset.month===month))}
filters.innerHTML=['All',...months].map(month=>`<button data-month="${month}">${month}</button>`).join('');
filters.addEventListener('click',event=>{const button=event.target.closest('[data-month]');if(button)renderArchive(button.dataset.month)});
renderArchive();
const initial=location.hash.slice(1);if(allStories.some(story=>story.id===initial))openStory(initial);
